/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2012-05-24 03:51:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.math.BigDecimal;
import org.apache.aries.samples.ariestrader.api.*;
import org.apache.aries.samples.ariestrader.api.persistence.*;
import org.apache.aries.samples.ariestrader.util.*;

public final class displayQuote_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

 
    TradeServicesManager tradeServicesManager = null;

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--\n");
      out.write(" Licensed to the Apache Software Foundation (ASF) under one or more\n");
      out.write("  contributor license agreements.  See the NOTICE file distributed with\n");
      out.write("  this work for additional information regarding copyright ownership.\n");
      out.write("  The ASF licenses this file to You under the Apache License, Version 2.0\n");
      out.write("  (the \"License\"); you may not use this file except in compliance with\n");
      out.write("  the License.  You may obtain a copy of the License at\n");
      out.write("\n");
      out.write("      http://www.apache.org/licenses/LICENSE-2.0\n");
      out.write("\n");
      out.write("  Unless required by applicable law or agreed to in writing, software\n");
      out.write("  distributed under the License is distributed on an \"AS IS\" BASIS,\n");
      out.write("  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n");
      out.write("  See the License for the specific language governing permissions and\n");
      out.write("  limitations under the License.\n");
      out.write("-->\n");
      out.write("\n");
      out.write('\n');
 
    String symbol = request.getParameter("symbol");

    if (tradeServicesManager == null) {
        tradeServicesManager = TradeServiceUtilities.getTradeServicesManager();
    }
    TradeServices tradeServices = tradeServicesManager.getTradeServices();

	try { 
		QuoteDataBean quoteData = tradeServices.getQuote(symbol);

 
      out.write("\n");
      out.write("<TR align=\"center\" bgcolor=\"#fafcb6\">\n");
      out.write("\t<TD>");
      out.print( FinancialUtils.printQuoteLink(quoteData.getSymbol()) );
      out.write("</TD>\n");
      out.write("\t<TD>");
      out.print( quoteData.getCompanyName());
      out.write("</TD>\n");
      out.write("\t<TD>");
      out.print( quoteData.getVolume());
      out.write("</TD>\n");
      out.write("\t<TD>");
      out.print( quoteData.getLow() + " - " + quoteData.getHigh());
      out.write("</TD>\n");
      out.write("\t<TD nowrap>");
      out.print( quoteData.getOpen());
      out.write("</TD>\n");
      out.write("\t<TD>$ ");
      out.print( quoteData.getPrice());
      out.write("</TD>\n");
      out.write("\t<TD>");
      out.print( FinancialUtils.printGainHTML(new BigDecimal(quoteData.getChange())) );
      out.write('\n');
      out.write('	');
      out.print( FinancialUtils.printGainPercentHTML( FinancialUtils.computeGainPercent(quoteData.getPrice(), quoteData.getOpen())) );
      out.write("</TD>\n");
      out.write("\t<TD>\n");
      out.write("\t<FORM action=\"\"><INPUT type=\"submit\" name=\"action\" value=\"buy\"><INPUT\n");
      out.write("\t\ttype=\"hidden\" name=\"symbol\" value=\"");
      out.print( quoteData.getSymbol());
      out.write("\"><INPUT\n");
      out.write("\t\tsize=\"4\" type=\"text\" name=\"quantity\" value=\"100\"></FORM>\n");
      out.write("\t</TD>\n");
      out.write("</TR>\n");
      out.write("\n");

	}
	catch (Exception e)
	{
		Log.error("displayQuote.jsp  exception", e);
	}

      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
