/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2012-05-24 03:48:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Collection;
import java.util.Iterator;
import java.math.BigDecimal;
import org.apache.aries.samples.ariestrader.api.*;
import org.apache.aries.samples.ariestrader.api.persistence.*;
import org.apache.aries.samples.ariestrader.util.*;

public final class tradehome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {



  BigDecimal computeHoldingsTotal(Collection holdingDataBeans) {
      BigDecimal holdingsTotal = new BigDecimal(0.0).setScale(2);
      if (holdingDataBeans == null)
          return holdingsTotal;
      Iterator it = holdingDataBeans.iterator();
      while (it.hasNext()) {
          HoldingDataBean holdingData = (HoldingDataBean) it.next();
          BigDecimal total =
          holdingData.getPurchasePrice().multiply(new BigDecimal(holdingData.getQuantity()));
          holdingsTotal = holdingsTotal.add(total);
      }
      return holdingsTotal.setScale(2);
  }


  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--\n");
      out.write(" Licensed to the Apache Software Foundation (ASF) under one or more\n");
      out.write("  contributor license agreements.  See the NOTICE file distributed with\n");
      out.write("  this work for additional information regarding copyright ownership.\n");
      out.write("  The ASF licenses this file to You under the Apache License, Version 2.0\n");
      out.write("  (the \"License\"); you may not use this file except in compliance with\n");
      out.write("  the License.  You may obtain a copy of the License at\n");
      out.write("\n");
      out.write("      http://www.apache.org/licenses/LICENSE-2.0\n");
      out.write("\n");
      out.write("  Unless required by applicable law or agreed to in writing, software\n");
      out.write("  distributed under the License is distributed on an \"AS IS\" BASIS,\n");
      out.write("  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n");
      out.write("  See the License for the specific language governing permissions and\n");
      out.write("  limitations under the License.\n");
      out.write("-->\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">\n");
      out.write("<HTML>\n");
      out.write("<HEAD>\n");
      out.write("<META http-equiv=\"Content-Style-Type\" content=\"text/css\">\n");
      out.write("<TITLE>Welcome to AriesTrader</TITLE>\n");
      out.write("<LINK rel=\"stylesheet\" href=\"style.css\" type=\"text/css\" />\n");
      out.write("</HEAD>\n");
      out.write("<BODY bgcolor=\"#ffffff\" link=\"#000099\" vlink=\"#000099\">\n");
      out.write("\n");
      java.lang.String results = null;
      results = (java.lang.String) _jspx_page_context.getAttribute("results", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (results == null){
        throw new java.lang.InstantiationException("bean results not found within scope");
      }
      out.write('\n');
      org.apache.aries.samples.ariestrader.api.persistence.AccountDataBean accountData = null;
      accountData = (org.apache.aries.samples.ariestrader.api.persistence.AccountDataBean) _jspx_page_context.getAttribute("accountData", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (accountData == null){
        throw new java.lang.InstantiationException("bean accountData not found within scope");
      }
      out.write('\n');
      java.util.Collection holdingDataBeans = null;
      holdingDataBeans = (java.util.Collection) _jspx_page_context.getAttribute("holdingDataBeans", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (holdingDataBeans == null){
        throw new java.lang.InstantiationException("bean holdingDataBeans not found within scope");
      }
      out.write('\n');
      out.write("\n");
      out.write("<TABLE height=\"54\">\n");
      out.write("\t<TBODY>\n");
      out.write("\t\t<TR>\n");
      out.write("\t\t\t<TD bgcolor=\"#c93333\" align=\"left\" width=\"640\" height=\"10\" colspan=5><B><FONT\n");
      out.write("\t\t\t\tcolor=\"#ffffff\">AriesTrader Home</FONT></B></TD>\n");
      out.write("\t\t\t<TD align=\"center\" bgcolor=\"#000000\" width=\"100\" height=\"10\"><FONT\n");
      out.write("\t\t\t\tcolor=\"#ffffff\"><B>AriesTrader</B></FONT></TD>\n");
      out.write("\t\t</TR>\n");
      out.write("\t\t<TR align=\"left\">\n");
      out.write("\t\t\t<TD><B><A href=\"app?action=home\">Home</A></B><B> </B></TD>\n");
      out.write("\t\t\t<TD><B><A href=\"app?action=account\">Account</A></B><B> </B></TD>\n");
      out.write("\t\t\t<TD><B><A href=\"app?action=portfolio\">Portfolio</A></B><B> </B></TD>\n");
      out.write("\t\t\t<TD><B><A href=\"app?action=quotes&amp;symbols=s:0,s:1,s:2,s:3,s:4\">Quotes/Trade</A></B></TD>\n");
      out.write("\t\t\t<TD><B><A href=\"app?action=logout\">Logoff</A></B></TD>\n");
      out.write("\t\t\t<TD></TD>\n");
      out.write("\t\t</TR>\n");
      out.write("\t\t<TR>\n");
      out.write("\t\t\t<TD align=\"right\" colspan=\"6\">\n");
      out.write("\t\t\t<HR>\n");
      out.write("\t\t\t<FONT color=\"#ff0000\" size=\"-2\">");
      out.print( new java.util.Date() );
      out.write("</FONT></TD>\n");
      out.write("\t\t</TR>\n");
      out.write("\t\t");

Collection closedOrders = (Collection)request.getAttribute("closedOrders");
if ( (closedOrders != null) && (closedOrders.size()>0) )
{

      out.write("\n");
      out.write("\t\t<TR>\n");
      out.write("\t\t\t<TD colspan=\"6\" bgcolor=\"#ff0000\"><BLINK><B><FONT color=\"#ffffff\">Alert:\n");
      out.write("\t\t\tThe following Order(s) have completed.</FONT></B></BLINK></TD>\n");
      out.write("\t\t</TR>\n");
      out.write("\t\t<TR align=\"center\">\n");
      out.write("\t\t\t<TD colspan=\"6\">\n");
      out.write("\t\t\t<TABLE border=\"1\" style=\"font-size: smaller\">\n");
      out.write("\t\t\t\t<TBODY>\n");
      out.write("\t\t\t\t\t");

	Iterator it = closedOrders.iterator();
	while (it.hasNext() )
	{
		OrderDataBean closedOrderData = (OrderDataBean)it.next();

      out.write("\n");
      out.write("\t\t\t\t\t<TR align=\"center\">\n");
      out.write("\t\t\t\t\t\t<TD><A href=\"docs/glossary.html\">order ID</A></TD>\n");
      out.write("\t\t\t\t\t\t<TD><A href=\"docs/glossary.html\">order status</A></TD>\n");
      out.write("\t\t\t\t\t\t<TD><A href=\"docs/glossary.html\">creation date</A></TD>\n");
      out.write("\t\t\t\t\t\t<TD><A href=\"docs/glossary.html\">completion date</A></TD>\n");
      out.write("\t\t\t\t\t\t<TD><A href=\"docs/glossary.html\">txn fee</A></TD>\n");
      out.write("\t\t\t\t\t\t<TD><A href=\"docs/glossary.html\">type</A></TD>\n");
      out.write("\t\t\t\t\t\t<TD><A href=\"docs/glossary.html\">symbol</A></TD>\n");
      out.write("\t\t\t\t\t\t<TD><A href=\"docs/glossary.html\">quantity</A></TD>\n");
      out.write("\t\t\t\t\t</TR>\n");
      out.write("\t\t\t\t\t<TR align=\"center\">\n");
      out.write("\t\t\t\t\t\t<TD>");
      out.print( closedOrderData.getOrderID());
      out.write("</TD>\n");
      out.write("\t\t\t\t\t\t<TD>");
      out.print( closedOrderData.getOrderStatus());
      out.write("</TD>\n");
      out.write("\t\t\t\t\t\t<TD>");
      out.print( closedOrderData.getOpenDate());
      out.write("</TD>\n");
      out.write("\t\t\t\t\t\t<TD>");
      out.print( closedOrderData.getCompletionDate());
      out.write("</TD>\n");
      out.write("\t\t\t\t\t\t<TD>");
      out.print( closedOrderData.getOrderFee());
      out.write("</TD>\n");
      out.write("\t\t\t\t\t\t<TD>");
      out.print( closedOrderData.getOrderType());
      out.write("</TD>\n");
      out.write("\t\t\t\t\t\t<TD>");
      out.print( FinancialUtils.printQuoteLink(closedOrderData.getSymbol()));
      out.write("</TD>\n");
      out.write("\t\t\t\t\t\t<TD>");
      out.print( closedOrderData.getQuantity());
      out.write("</TD>\n");
      out.write("\t\t\t\t\t</TR>\n");
      out.write("\t\t\t\t\t");

	}

      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t</TBODY>\n");
      out.write("\t\t\t</TABLE>\n");
      out.write("\t\t\t</TD>\n");
      out.write("\t\t</TR>\n");
      out.write("\t\t");

}

      out.write("\n");
      out.write("\t</TBODY>\n");
      out.write("</TABLE>\n");
      out.write("<TABLE width=\"636\">\n");
      out.write("\t<TBODY>\n");
      out.write("\t\t<TR>\n");
      out.write("\t\t\t<TD valign=\"top\" width=\"377\">\n");
      out.write("\t\t\t<TABLE width=\"384\">\n");
      out.write("\t\t\t\t<TBODY>\n");
      out.write("\t\t\t\t\t<TR>\n");
      out.write("\t\t\t\t\t\t<TD colspan=\"3\"><B>Welcome &nbsp;");
      out.print( accountData.getProfileID() );
      out.write(",</B></TD>\n");
      out.write("\t\t\t\t\t</TR>\n");
      out.write("\t\t\t\t\t<TR>\n");
      out.write("\t\t\t\t\t\t<TD width=\"133\"></TD>\n");
      out.write("\t\t\t\t\t\t<TD width=\"22\"></TD>\n");
      out.write("\t\t\t\t\t\t<TD width=\"212\"></TD>\n");
      out.write("\t\t\t\t\t</TR>\n");
      out.write("\t\t\t\t\t<TR>\n");
      out.write("\t\t\t\t\t\t<TD colspan=\"3\" align=\"left\" bgcolor=\"#cccccc\"><B> User Statistics\n");
      out.write("\t\t\t\t\t\t</B></TD>\n");
      out.write("\t\t\t\t\t</TR>\n");
      out.write("\t\t\t\t\t<TR>\n");
      out.write("\t\t\t\t\t\t<TD align=\"right\" valign=\"top\" width=\"133\"><A\n");
      out.write("\t\t\t\t\t\t\thref=\"docs/glossary.html\">account ID:<BR>\n");
      out.write("\t\t\t\t\t\t</A><A href=\"docs/glossary.html\">account created:</A><BR>\n");
      out.write("\t\t\t\t\t\t<A href=\"docs/glossary.html\">total logins:</A><BR>\n");
      out.write("\t\t\t\t\t\t<A href=\"docs/glossary.html\">session created:</A><BR>\n");
      out.write("\t\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t\t\t<TD width=\"22\"></TD>\n");
      out.write("\t\t\t\t\t\t<TD align=\"left\" width=\"212\">");
      out.print( accountData.getAccountID()
);
      out.write("<BR>\n");
      out.write("\t\t\t\t\t\t");
      out.print( accountData.getCreationDate()
);
      out.write("<BR>\n");
      out.write("\t\t\t\t\t\t");
      out.print( accountData.getLoginCount()
);
      out.write("<BR>\n");
      out.write("\t\t\t\t\t\t");
      out.print( (java.util.Date) session.getAttribute("sessionCreationDate")
);
      out.write("<BR>\n");
      out.write("\t\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t\t</TR>\n");
      out.write("\t\t\t\t\t<TR>\n");
      out.write("\t\t\t\t\t\t<TD width=\"133\"></TD>\n");
      out.write("\t\t\t\t\t\t<TD width=\"22\"></TD>\n");
      out.write("\t\t\t\t\t\t<TD width=\"212\"></TD>\n");
      out.write("\t\t\t\t\t</TR>\n");
      out.write("\t\t\t\t\t<TR>\n");
      out.write("\t\t\t\t\t\t<TD colspan=\"3\" bgcolor=\"#cccccc\"><B>Account Summary </B></TD>\n");
      out.write("\t\t\t\t\t</TR>\n");
      out.write("\t\t\t\t\t<TR>\n");
      out.write("\t\t\t\t\t\t<TD align=\"right\" valign=\"top\" width=\"133\"><A\n");
      out.write("\t\t\t\t\t\t\thref=\"docs/glossary.html\"> cash balance:</A><BR>\n");
      out.write("\t\t\t\t\t\t<A href=\"docs/glossary.html\">number of holdings:</A><BR>\n");
      out.write("\t\t\t\t\t\t<A href=\"docs/glossary.html\">total of holdings:<BR>\n");
      out.write("\t\t\t\t\t\tsum of cash/holdings<BR>\n");
      out.write("\t\t\t\t\t\topening balance:<BR>\n");
      out.write("\t\t\t\t\t\t</A>\n");
      out.write("\t\t\t\t\t\t<HR>\n");
      out.write("\t\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t\t\t<TD width=\"22\"></TD>\n");
      out.write("\t\t\t\t\t\t<TD align=\"left\" valign=\"top\" width=\"212\">");
 
                        	BigDecimal openBalance = accountData.getOpenBalance();
                        	BigDecimal balance = accountData.getBalance();
                        	BigDecimal holdingsTotal = computeHoldingsTotal(holdingDataBeans);
                        	BigDecimal sumOfCashHoldings = balance.add(holdingsTotal);
                        	BigDecimal gain = FinancialUtils.computeGain(sumOfCashHoldings, openBalance);
							BigDecimal gainPercent = FinancialUtils.computeGainPercent(sumOfCashHoldings, openBalance);
                         
      out.write('$');
      out.write(' ');
      out.print( balance );
      out.write("<BR>\n");
      out.write("\t\t\t\t\t\t");
      out.print( holdingDataBeans.size());
      out.write("<BR>\n");
      out.write("\t\t\t\t\t\t$ ");
      out.print( holdingsTotal );
      out.write("<BR>\n");
      out.write("\t\t\t\t\t\t$ ");
      out.print( sumOfCashHoldings );
      out.write("<BR>\n");
      out.write("\t\t\t\t\t\t$ ");
      out.print( openBalance);
      out.write("<BR>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<HR>\n");
      out.write("\t\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t\t</TR>\n");
      out.write("\t\t\t\t\t<TR>\n");
      out.write("\t\t\t\t\t\t<TD valign=\"top\" align=\"right\"><A href=\"docs/glossary.html\">current\n");
      out.write("\t\t\t\t\t\tgain/(loss):</A></TD>\n");
      out.write("\t\t\t\t\t\t<TD></TD>\n");
      out.write("\t\t\t\t\t\t<TD valign=\"top\">$ <B>");
      out.print( FinancialUtils.printGainHTML(gain) );
      out.write(' ');
      out.print( FinancialUtils.printGainPercentHTML(gainPercent) );
      out.write("</B></TD>\n");
      out.write("\t\t\t\t\t</TR>\n");
      out.write("\t\t\t\t</TBODY>\n");
      out.write("\t\t\t</TABLE>\n");
      out.write("\t\t\t</TD>\n");
      out.write("\t\t\t<TD align=\"center\" valign=\"top\" bgcolor=\"#ffffff\" width=\"236\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "marketSummary.jsp", out, false);
      out.write(" <BR>\n");
      out.write("\t\t\t</TD>\n");
      out.write("\t\t</TR>\n");
      out.write("\t</TBODY>\n");
      out.write("</TABLE>\n");
      out.write("<TABLE height=\"54\" style=\"font-size: smaller\">\n");
      out.write("\t<TBODY>\n");
      out.write("\t\t<TR>\n");
      out.write("\t\t\t<TD colspan=\"2\">\n");
      out.write("\t\t\t<HR>\n");
      out.write("\t\t\t</TD>\n");
      out.write("\t\t</TR>\n");
      out.write("\t\t<TR>\n");
      out.write("\t\t\t<TD colspan=\"2\">\n");
      out.write("\t\t\t<TABLE width=\"100%\" style=\"font-size: smaller\">\n");
      out.write("\t\t\t\t<TBODY>\n");
      out.write("\t\t\t\t\t<TR>\n");
      out.write("\t\t\t\t\t\t<TD>Note: Click any <A href=\"docs/glossary.html\">symbol</A> for a\n");
      out.write("\t\t\t\t\t\tquote or to trade.</TD>\n");
      out.write("\t\t\t\t\t\t<TD align=\"right\">\n");
      out.write("\t\t\t\t\t\t<FORM action=\"\"><INPUT type=\"submit\" name=\"action\" value=\"quotes\">\n");
      out.write("\t\t\t\t\t\t<INPUT size=\"20\" type=\"text\" name=\"symbols\"\n");
      out.write("\t\t\t\t\t\t\tvalue=\"s:0, s:1, s:2, s:3, s:4\"></FORM>\n");
      out.write("\t\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t\t</TR>\n");
      out.write("\t\t\t\t</TBODY>\n");
      out.write("\t\t\t</TABLE>\n");
      out.write("\t\t\t</TD>\n");
      out.write("\t\t</TR>\n");
      out.write("\t\t<TR>\n");
      out.write("\t\t\t<TD bgcolor=\"#c93333\" align=\"left\" width=\"640\" height=\"10\"><B><FONT\n");
      out.write("\t\t\t\tcolor=\"#ffffff\">AriesTrader Home</FONT></B></TD>\n");
      out.write("\t\t\t<TD align=\"center\" bgcolor=\"#000000\" width=\"100\" height=\"10\"><FONT\n");
      out.write("\t\t\t\tcolor=\"#ffffff\"><B>AriesTrader</B></FONT></TD>\n");
      out.write("\t\t</TR>\n");
      out.write("\t</TBODY>\n");
      out.write("</TABLE>\n");
      out.write("</BODY>\n");
      out.write("</HTML>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
