/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2012-05-24 03:27:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--\n");
      out.write(" Licensed to the Apache Software Foundation (ASF) under one or more\n");
      out.write("  contributor license agreements.  See the NOTICE file distributed with\n");
      out.write("  this work for additional information regarding copyright ownership.\n");
      out.write("  The ASF licenses this file to You under the Apache License, Version 2.0\n");
      out.write("  (the \"License\"); you may not use this file except in compliance with\n");
      out.write("  the License.  You may obtain a copy of the License at\n");
      out.write("\n");
      out.write("      http://www.apache.org/licenses/LICENSE-2.0\n");
      out.write("\n");
      out.write("  Unless required by applicable law or agreed to in writing, software\n");
      out.write("  distributed under the License is distributed on an \"AS IS\" BASIS,\n");
      out.write("  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n");
      out.write("  See the License for the specific language governing permissions and\n");
      out.write("  limitations under the License.\n");
      out.write("-->\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">\n");
      out.write("<HTML>\n");
      out.write("<HEAD>\n");
      out.write("<TITLE>Trade Login</TITLE>\n");
      out.write("<LINK rel=\"stylesheet\" href=\"style.css\" type=\"text/css\" />\n");
      out.write("</HEAD>\n");
      out.write("<BODY bgcolor=\"#ffffff\" link=\"#000099\">\n");
      out.write("\n");
      out.write("<TABLE style=\"font-size: smaller\">\n");
      out.write("\t<TBODY>\n");
      out.write("\t\t<TR>\n");
      out.write("\t\t\t<TD bgcolor=\"#c93333\" align=\"left\" width=\"640\" height=\"10\"><B><FONT\n");
      out.write("\t\t\t\tcolor=\"#ffffff\">AriesTrader Login</FONT></B></TD>\n");
      out.write("\t\t\t<TD align=\"center\" bgcolor=\"#000000\" width=\"100\" height=\"10\"><FONT\n");
      out.write("\t\t\t\tcolor=\"#ffffff\"><B>AriesTrader</B></FONT></TD>\n");
      out.write("\t\t</TR>\n");
      out.write("\t</TBODY>\n");
      out.write("</TABLE>\n");
      out.write("<TABLE width=\"100%\" height=\"30\">\n");
      out.write("\t<TBODY>\n");
      out.write("\t\t<TR>\n");
      out.write("\t\t\t<TD></TD>\n");
      out.write("\t\t\t<TD><FONT color=\"#ff0033\"><FONT color=\"#ff0033\"><FONT color=\"#ff0033\">");
 String results;
results = (String) request.getAttribute("results");
if ( results != null )out.print(results);

      out.write("</FONT></FONT></FONT></TD>\n");
      out.write("\t\t\t<TD></TD>\n");
      out.write("\t\t</TR>\n");
      out.write("\t</TBODY>\n");
      out.write("</TABLE>\n");
      out.write("<DIV align=\"left\"></DIV>\n");
      out.write("<TABLE width=\"616\">\n");
      out.write("\t<TBODY>\n");
      out.write("\t\t<TR>\n");
      out.write("\t\t\t<TD width=\"2%\" bgcolor=\"#e7e4e7\" rowspan=\"3\"></TD>\n");
      out.write("\t\t\t<TD width=\"98%\"><B>Log in</B>\n");
      out.write("\t\t\t<HR>\n");
      out.write("\t\t\t</TD>\n");
      out.write("\t\t</TR>\n");
      out.write("\t\t<TR>\n");
      out.write("\t\t\t<TD align=\"right\"><FONT size=\"-1\">Username &nbsp; &nbsp; &nbsp;&nbsp;\n");
      out.write("\t\t\t&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Password &nbsp; &nbsp; &nbsp;\n");
      out.write("\t\t\t&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;\n");
      out.write("\t\t\t&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</FONT></TD>\n");
      out.write("\t\t</TR>\n");
      out.write("\t\t<TR>\n");
      out.write("\t\t\t<TD align=\"right\">\n");
      out.write("\t\t\t<FORM action=\"app\" method=\"POST\"><INPUT size=\"10\" type=\"text\"\n");
      out.write("\t\t\t\tname=\"uid\" value=\"uid:0\"> &nbsp; &nbsp; &nbsp; &nbsp; <INPUT\n");
      out.write("\t\t\t\tsize=\"10\" type=\"password\" name=\"passwd\" value=\"xxx\"> &nbsp; <INPUT\n");
      out.write("\t\t\t\ttype=\"submit\" value=\"Log in\"><INPUT type=\"hidden\" name=\"action\"\n");
      out.write("\t\t\t\tvalue=\"login\"></FORM>\n");
      out.write("\t\t\t</TD>\n");
      out.write("\t\t</TR>\n");
      out.write("\t</TBODY>\n");
      out.write("</TABLE>\n");
      out.write("<TABLE width=\"616\">\n");
      out.write("\t<TBODY>\n");
      out.write("\t\t<TR>\n");
      out.write("\t\t\t<TD width=\"2%\"></TD>\n");
      out.write("\t\t\t<TD width=\"98%\">\n");
      out.write("\t\t\t<HR>\n");
      out.write("\t\t\t</TD>\n");
      out.write("\t\t</TR>\n");
      out.write("\t\t<TR>\n");
      out.write("\t\t\t<TD bgcolor=\"#e7e4e7\" rowspan=\"4\"></TD>\n");
      out.write("\t\t\t<TD><B><FONT size=\"-1\" color=\"#000000\">First time user? &nbsp;Please\n");
      out.write("\t\t\tRegister</FONT></B></TD>\n");
      out.write("\t\t</TR>\n");
      out.write("\t\t<TR>\n");
      out.write("\t\t\t<TD></TD>\n");
      out.write("\t\t</TR>\n");
      out.write("\t\t<TR>\n");
      out.write("\t\t\t<TD align=\"right\">\n");
      out.write("\t\t\t<BLOCKQUOTE><A href=\"register.jsp\">Register&nbsp;With&nbsp;AriesTrader</A>\n");
      out.write("\t\t\t</BLOCKQUOTE>\n");
      out.write("\t\t\t</TD>\n");
      out.write("\t\t</TR>\n");
      out.write("\t\t<TR>\n");
      out.write("\t\t\t<TD>\n");
      out.write("\t\t\t<HR>\n");
      out.write("\t\t\t</TD>\n");
      out.write("\t\t</TR>\n");
      out.write("\t</TBODY>\n");
      out.write("</TABLE>\n");
      out.write("<TABLE height=\"54\" style=\"font-size: smaller\">\n");
      out.write("\t<TBODY>\n");
      out.write("\t\t<TR>\n");
      out.write("\t\t\t<TD colspan=\"2\">\n");
      out.write("\t\t\t<HR>\n");
      out.write("\t\t\t</TD>\n");
      out.write("\t\t</TR>\n");
      out.write("\t\t<TR>\n");
      out.write("\t\t\t<TD colspan=\"2\"></TD>\n");
      out.write("\t\t</TR>\n");
      out.write("\t\t<TR>\n");
      out.write("\t\t\t<TD bgcolor=\"#c93333\" align=\"left\" width=\"640\" height=\"10\"><B><FONT\n");
      out.write("\t\t\t\tcolor=\"#ffffff\">AriesTrader Login</FONT></B></TD>\n");
      out.write("\t\t\t<TD align=\"center\" bgcolor=\"#000000\" width=\"100\" height=\"10\"><FONT\n");
      out.write("\t\t\t\tcolor=\"#ffffff\"><B>AriesTrader</B></FONT></TD>\n");
      out.write("\t\t</TR>\n");
      out.write("\t</TBODY>\n");
      out.write("</TABLE>\n");
      out.write("</BODY>\n");
      out.write("</HTML>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
